apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: "exampledb"
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
---  
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-deployment
spec:
  replicas: 1  # Cassandraのレプリカ数を4に設定
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:latest  # Cassandraの公式Dockerイメージを使用
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "CassandraCluster"
        - name: CASSANDRA_SEEDS
          value: "cassandra-0.cassandra.default.svc.cluster.local"
        ports:
        - containerPort: 7000  # クラスター通信用
        - containerPort: 9042  # CQLクライアント用
        resources:  # メモリリクエストとリミットを設定
          requests:
            memory: "2Gi"
          limits:
            memory: "3Gi"        
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  ports:
  - port: 9042
    targetPort: 9042
  selector:
    app: cassandra
  clusterIP: None  # Headless Serviceとして定義